language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
branches:
  only:
  - master
  - release
  - travis
install:
- pip install -r requirements-dev.txt
- pip install coveralls
script: py.test --cov ecs_deploy.py --cov-report term-missing --pep8
after_success:
- coveralls
notifications:
  slack:
    rooms:
      secure: Tok8grsXdoAXuWhig0fO66CLW4SvQsSaRZJ0ZZ/2bkt276LrggcgdNYwSJs4qDuMYz1/eMFASLe0obfgd0EKtliHIZFQLW05aoLKABj6N0k0XhIrqkWWhwhYdL+P8rnsr2VPNEFcX+iXY9V93KBnCBnrixH+J6VaMBr/gvHEZuZbM+gWWDeN/C1P+4T/NtmsvQmSt1jv3pskn7MKpbikIwDNyTvvH1jVPu1mZuaZ0DP2WMO8Pqr1fXsQ3IWlNVULx/JK9wwYRDcCK41qKIjYxUXMYUTkPdxn4aBtJ/oiSNasLwB06x9PYTkbgVoXouj6yxRqJduSR/qCZ/jfaYGAWOhtPVbK3dbUv/qi6gy0Fa62Qd6uFVykUinNPTWz+uNfpmwyO8ZNSKAuyVRMQGJgY9jSXpWaVFQjZVrjyPjfGwo51sqvUYgL3rA8Zq70T4m/Nwb/f7hxHCWZkW0dNopuT3sviBuRBsvdyKvqh51CqKGWI9qV3nxltXjZ9v8GClXXs5PL/spvbmUwa91vgqUSLrK+RttETGxAjoak11A9/SLpXmJcBNBUVMG2xCGUlFR01njyUnPkgSWJI+8oKG1jWER0CvBMDHC8ydToE4sh6I8VPeX1s+G7wpHB9UBmWzOU05SMxrtlzWnDD+NzJTag8/HXN5FIs7DpNoSxTei/lVs=
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: cuttlesoft
  password:
    secure: oI1Nk6gLX9V3N1mIJdOOVmShL8ey28Ode6jjsspvrNSqot0AJPyg343zzB2x5kcoJ5MY6aKcpUY56AIGxkjy00/wlcMcXSXhFQ8p1470wYoMwrgwGVX9/EBydEedWVaZqNgmQp4YUQywozkHfGNpjYbPUboQ0HtSb2EmvDsCFAIohSMinjsKlutJFVYB9xeqPVa9yFRaWl5Ohku++IESP/IG2wu8gJLggKf7uHIhWcDrtPcl3YCrZtmkR6H7Z9c/WuyvovvLrQBtCeZEQLOvIePzrVw1wGxKXegDynh+xXAOFQPNBoGTlUIfMjoaMIU8W7bgOBiqDGvhxQ8JmwOj1FDn+ghTUNRsun4zZyRkAshWa5mhhzFM1NskNP4AWCNUw+WT5OhE68V+sflXgSAQS9PU1VL4ai2txMX7pBYU8jJ6gbX225Ef7xDT7KW/2TZu5B+oOtt1ogH8KtYCkbY7Fek+gSgDOIB4eW31tw1iy6E9MLnF9N18lX+Xoplur+U8SdseAxqAUDufBZ6X8Ny48gkLG7NCCC5mpPMK0ZsNeOdfAsFkNqCuDfzN4gh9dpH276XQu04FAwIQQVK+FZeGiPnli0txasqfoqhFBvSNr5ze99ZzHYkPT5CmX5f5q3L7Nhgbck3pEYzqkdOm0cx4vU2UkVFxbwGK1YxR7wV1nxg=
  on:
    distributions: sdist bdist_wheel
    repo: cuttlesoft/ecs-deploy.py
    branch: master
