language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
branches:
  only:
  - master
  - release
  - travis
install:
- pip install -r requirements-dev.txt
- pip install coveralls
script: py.test --cov ecs_deploy.py --cov-report term-missing --pep8
after_success:
- coveralls
notifications:
  slack:
    rooms:
      secure: Tok8grsXdoAXuWhig0fO66CLW4SvQsSaRZJ0ZZ/2bkt276LrggcgdNYwSJs4qDuMYz1/eMFASLe0obfgd0EKtliHIZFQLW05aoLKABj6N0k0XhIrqkWWhwhYdL+P8rnsr2VPNEFcX+iXY9V93KBnCBnrixH+J6VaMBr/gvHEZuZbM+gWWDeN/C1P+4T/NtmsvQmSt1jv3pskn7MKpbikIwDNyTvvH1jVPu1mZuaZ0DP2WMO8Pqr1fXsQ3IWlNVULx/JK9wwYRDcCK41qKIjYxUXMYUTkPdxn4aBtJ/oiSNasLwB06x9PYTkbgVoXouj6yxRqJduSR/qCZ/jfaYGAWOhtPVbK3dbUv/qi6gy0Fa62Qd6uFVykUinNPTWz+uNfpmwyO8ZNSKAuyVRMQGJgY9jSXpWaVFQjZVrjyPjfGwo51sqvUYgL3rA8Zq70T4m/Nwb/f7hxHCWZkW0dNopuT3sviBuRBsvdyKvqh51CqKGWI9qV3nxltXjZ9v8GClXXs5PL/spvbmUwa91vgqUSLrK+RttETGxAjoak11A9/SLpXmJcBNBUVMG2xCGUlFR01njyUnPkgSWJI+8oKG1jWER0CvBMDHC8ydToE4sh6I8VPeX1s+G7wpHB9UBmWzOU05SMxrtlzWnDD+NzJTag8/HXN5FIs7DpNoSxTei/lVs=
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: cuttlesoft
  password:
    secure: NZGVeI1ma8M8zM01/M3psruotHiHbFy7O9tNwmrfv/tPbdVlkwm9xYa/W9rFUtAfDJp77G0H+oi0uivu58bHTLE5tF2FdwQQzuxKK6tX2DMCDDEEV5q/coOF9+yrXYAFBdDgXKgifCsjdyMaocdJ+8N1FcB1mN+eshQ2l8qObT0A6fxijG8l4pDBD5wYCjcX0x7+uv5lmjhxL/H1Ooik8p4ALr0AB4csm8DrBiPlHQZLkg9nGpWY9D1ForVp+rzciP+DANfPtpx5585eiZzNQso8GLFxd2UuXyTKZ59VmxHP7Vextq/L/e5nGfBpVwUbmpeNCrERrcmZE2Pxrp+BGxuA4H+QVdOpIPcrqloVqkkF5GCTUHweqUCHC9Z//V306xhVw5zlXGkmkdZiHKLyH8wc94EkP8wuOgBBJZRl/3ob1YUFmkbKJM5FWqHC5Q9LDAv8cR07tfZXK0YP6XHb8JRdR96GGR1BvvxtLpRDQueyWpu+TayASyv3uu2Yr/xHzxAeKXKaDHiJ33UOzojObNi4O6MIbkvJl0pupNll5ZLo9wpTcbVhjaMN949OU4a8R8DpB1CmhknXZddMq1Su02+7EUfzpyRbFvYyJK4K4axBn9fPfJUfs1OUwe+lF+IAFtcWW0JiHeIXdqRQAiL73t7wFLw1guU+e8r8D10lZiI=
  on:
    branch: master
    repo: cuttlesoft/ecs-deploy.py
